-- Centros de acopio adicionales — redes sociales 26-jun-2026
-- 104 puntos en Venezuela (excluye extranjero, transporte, médicos, duplicados v1)

with seed(nombre, organizacion, estado_vzla, direccion, lat, lng) as (
  values
    ('ISO HOME Prebo', 'ISO HOME', 'Carabobo', 'Urbanización Carabobo, Prebo, Valencia', 10.1501, -68.0012),
    ('ISO HOME El Nepe', 'ISO HOME', 'Carabobo', 'Supermercados TIO, Carretera Nacional Valencia-Guacara, Zona Industrial El Nepe', 10.1637, -67.9828),
    ('La Sagrada Familia', '', 'Aragua', 'Pasaje 13, Las Acacias, Maracay', 10.2373, -67.5934),
    ('Centro de Acopio Iglú Moda', '', 'Aragua', 'Avenida Roosevelt, Urbanización Nuevo Prado, Los Castaños, Maracay', 10.2509, -67.5982),
    ('Rock and Rolls Fit', 'Gym', 'Distrito Capital', '7.ª Avenida de Catia, Pérez Bonalde, Catia, Caracas', 10.4734, -66.9108),
    ('Páramo Qta Crespo', '', 'Distrito Capital', 'Avenida Oeste 18, San Martín, Barrio El Guarataro, Caracas', 10.487, -66.8924),
    ('Bullking Qta Crespo', 'Bullking', 'Distrito Capital', 'Bullking, Avenida Oeste 20, San Martín, Caracas', 10.4758, -66.8972),
    ('Bullking Paraíso', 'Bullking', 'Distrito Capital', 'Bullking, Avenida José Antonio Páez, Barrio Sinaí, Caracas', 10.4894, -66.902),
    ('Bullking Antímano', 'Bullking', 'Distrito Capital', 'Calle del Medio, Barrio La Cumbre, Mamera, Caracas', 10.4782, -66.9068),
    ('U.E.N. Ramón Isidro Montes', '', 'Distrito Capital', 'U.E.N. Ramón Isidro Montes, Calle Colombia, Pérez Bonalde, Caracas', 10.4918, -66.9116),
    ('Iglesia Catedral Proclamación', '', 'Lara', 'Catedral Proclamación, Av. Hermán Garmendia, Las Trinitarias, Barquisimeto', 10.0647, -69.3466),
    ('Acopio Parroquia Coche', '', 'Distrito Capital', 'Av. Miguel Otero Silva, Iglesia Santo Domingo Savio, Coche, Caracas', 10.4694, -66.898),
    ('Casa Verde Cincoxciento', '', 'Distrito Capital', 'Uozo Sano y Sabroso, 27A 21, Calle 42, Caracas', 10.483, -66.9028),
    ('Shopping Espacial Piso 2', '', 'Guárico', 'Farmacia Popular, Avenida Bolívar, Urbanización Doña Elvira, San Juan de los Morros', 9.9023, -67.3573),
    ('INTT San Juan de los Morros', 'INTT', 'Guárico', 'Redoma de La Bandera, Urbanización La Tropical 1, San Juan de los Morros', 9.9159, -67.3621),
    ('Farmatodo María de los Ángeles', 'Farmatodo', 'Barinas', 'Farmatodo, Avenida Fermín Toro, Barrio María de los Ángeles, Barinas', 8.6162, -70.1979),
    ('Estación de Servicio Pariapan', '', 'Barinas', 'E/S Pariapan, Avenida Fermín Toro, Barrio María de los Ángeles, Barinas', 8.6298, -70.2027),
    ('Alcaldía Juan Germán Roscio', '', 'Guárico', 'Avenida Cedeño, Centro, Urb. Doña Eva, San Juan de los Morros', 9.9071, -67.3533),
    ('Acopio Tamaca', '', 'Lara', 'Calle 1, Los Robles, Las Tunitas, Tamaca, Barquisimeto', 10.0743, -69.3618),
    ('Via Venetto', '', 'Guárico', 'Calle La Estrella, Centro, San Juan de los Morros', 9.9095, -67.3629),
    ('Gobernación de Guárico', '', 'Guárico', 'Avenida Sendrea, Centro, Urb. Doña Eva, San Juan de los Morros', 9.9231, -67.3445),
    ('Shopping Off San Juan', '', 'Guárico', 'Calle Infante, Centro, San Juan de los Morros', 9.9119, -67.3493),
    ('Una Mano Amiga Doña Elvira', 'Una Mano Amiga', 'Guárico', 'Avenida Bolívar, Urbanización Doña Elvira, San Juan de los Morros', 9.9007, -67.3541),
    ('Biblioteca Rómulo Gallegos SJM', '', 'Guárico', 'Biblioteca Rómulo Gallegos, Avenida Bolívar, Urbanización Doña Elvira, San Juan de los Morros', 9.9143, -67.3589),
    ('Una Mano Amiga Plaza Samanes', 'Una Mano Amiga', 'Guárico', 'Plaza de los Samanes, Av. Bolívar, Centro, San Juan de los Morros', 9.9031, -67.3637),
    ('Acopio Parroquia El Valle', '', 'Distrito Capital', 'Urbanización Pedro Freites, Fuerte Tiuna, Caracas', 10.4862, -66.8956),
    ('Bomberos de Guacara', '', 'Carabobo', 'Policía Municipal de Guacara, Carretera Nacional Valencia-Guacara, Negro Primero, Guacara', 10.1565, -67.9868),
    ('Colegio Caribe', '', 'Anzoátegui', 'Avenida 31 de Julio, Salamanca, Los Chuares, Puerto La Cruz', 10.2413, -64.6349),
    ('Academia Washington', '', 'Miranda', 'Calle C, Residencias Valle Arriba Golf, Los Campitos, Caracas', 10.4329, -66.8292),
    ('Capilla UCAB', 'UCAB', 'Miranda', 'Universidad Católica Andrés Bello, Avenida Teherán, Barrio Juana La Avanzadora, Caracas', 10.4465, -66.834),
    ('Logística Vincars', 'Vincars', 'Miranda', 'Calle Tamare, Macaracuay, Caracas', 10.4353, -66.8156),
    ('Plaza de la Bandera Pampatar', '', 'Nueva Esparta', '1.ª Etapa de Jorge Coll, Urbanización Playa El Ángel, Pampatar', 10.9758, -63.8498),
    ('Bomberos La Trinidad', '', 'Miranda', 'Bomberos de La Trinidad No. 17, Avenida Campo Alegre, Zona Industrial La Trinidad, Caracas', 10.4377, -66.8252),
    ('Gran Slam Covencaucho', '', 'Miranda', 'Covencaucho, Carretera Guarenas-Guatire, Urbanización Las Mesetas', 10.4265, -66.83),
    ('Centro Médico La Candelaria Cúa', '', 'Miranda', 'Cúa, Parroquia Cúa, Municipio Urdaneta', 10.4401, -66.8116),
    ('Iglesia Maranatha Valencia', '', 'Carabobo', 'Urb. Industrial Castillito, Calle Este Oeste 98, Valencia', 10.1549, -67.9836),
    ('Reda Estate', '', 'Carabobo', '4 Avenidas, Valencia', 10.1685, -67.9884),
    ('Frente CC Cima Barinas', '', 'Barinas', 'Frente al C.C. Cima, Avenida Andrés Bello, Alto Barinas Sur, Barinas', 8.6178, -70.2107),
    ('Alcaldía Roscio Nieves', '', 'Guárico', 'Calle Cedeño, San Juan de los Morros', 9.9199, -67.3613),
    ('Rectorado UNERG', 'UNERG', 'Guárico', 'Rectorado UNERG, San Juan de los Morros', 9.9087, -67.3429),
    ('Cafetín Clínica Santa Rosalía', '', 'Guárico', 'Piso 1, Clínica Santa Rosalía, San Juan de los Morros', 9.9223, -67.3477),
    ('Alcaldía de San Francisco', '', 'Zulia', 'Calle 171, La Coromoto, San Francisco, Zulia', 10.6666, -71.6116),
    ('U.E. Kavac Prebo', '', 'Carabobo', 'Urb. Prebo 2, Av. 112, Calle 141-B, Valencia', 10.1509, -67.994),
    ('Plaza Los Samanes SJM', '', 'Guárico', 'Plaza Los Samanes, San Juan de los Morros', 9.9135, -67.3621),
    ('Kawaii Multitienda Marconi', '', 'Carabobo', 'CC Marconi, Av. Bolívar Sur, Valencia', 10.1533, -67.9804),
    ('Cavernícolas Box', '', 'Guárico', 'Av. Rómulo Gallegos, San Juan de los Morros', 9.9159, -67.3485),
    ('Los Andes 2 San Diego', '', 'Carabobo', 'Los Andes 2, San Diego, Valencia', 10.1557, -67.99),
    ('Casona Universitaria', '', 'Guárico', 'Avenida Bolívar, Urbanización Doña Elvira, San Juan de los Morros', 9.9183, -67.3581),
    ('Callejón Gourmet', '', 'Guárico', 'Urbanización La Tropical 1, Centro, San Juan de los Morros', 9.9071, -67.3629),
    ('Centro de Acopio Despistaje Cáncer', '', 'Guárico', 'Despistaje Cáncer, Calle Los Puentes, Urbanización Doña Elvira, San Juan de los Morros', 9.9207, -67.3445),
    ('Ciudad Banesco', '', 'Miranda', 'Ciudad Banesco, Avenida Principal de Bello Monte, Bello Monte, Caracas', 10.4345, -66.8188),
    ('Cadoven Sambil', 'Cadoven', 'Miranda', 'Sambil Mall, Calle José de Jesús Ravelo, Proyecto V Centenario, Caracas', 10.4481, -66.8236),
    ('Fundación Juntos Se Puede', 'Fundación Juntos Se Puede', 'Carabobo', 'Fundación Juntos Se Puede, Calle 104 #54-31, Valencia', 10.1629, -67.9956),
    ('CC Borjas Xtrema', '', 'Zulia', 'Centro Comercial Borjas, Carretera H, Cabimas', 10.6562, -71.6228),
    ('Iglesia La Chiquinquirá', '', 'Distrito Capital', 'Iglesia Nuestra Señora de La Chiquinquirá, Avenida Andrés Bello, San Rafael de La Florida, Caracas', 10.4838, -66.8956),
    ('Pepitería 13', '', 'Miranda', 'Pepitería 13, Calle Madrid, Las Mercedes, Caracas', 10.4281, -66.8196),
    ('Instituto Diseño Caracas', '', 'Distrito Capital', 'Instituto Diseño Caracas, Calle Ávila, La Castellana, Caracas', 10.4862, -66.9052),
    ('Academia Merici', '', 'Miranda', 'Academia Merici, Calle Central, Cerro Verde, Caracas', 10.4305, -66.8292),
    ('UNERG Paraíso', 'UNERG', 'Guárico', 'Universidad Rómulo Gallegos, Calle Cecilio Acosta, Urbanización Cristo Rey, San Juan de los Morros', 9.9191, -67.3645),
    ('ULA Paramillo', 'ULA', 'Táchira', 'Universidad de Los Andes, Avenida ULA, Paramillo, San Cristóbal', 7.7666, -72.2178),
    ('Acopio Abasto Caracas', '', 'Distrito Capital', 'Av. Principal Negro Primero, Negro Primero, Parroquia Corazón de Jesús, Caracas', 10.491, -66.9012),
    ('Acopio Candelaria Galerías Ávila', '', 'Distrito Capital', 'Par de arepas diagonal al estacionamiento del CC Galerías Ávila, Caracas', 10.4798, -66.906),
    ('Capilla Divina Pastora Caracas', '', 'Distrito Capital', 'Capilla de la Divina Pastora, Calle Amparo, Encarnación-Regina, Caracas', 10.4686, -66.9108),
    ('Acopio Las Mercedes Barriot', '', 'Miranda', 'Barriot, Calle Madrid, Las Mercedes, Caracas', 10.4377, -66.8116),
    ('TSJ San Juan de Colón', 'TSJ', 'Táchira', 'Calle 3, Casco Central, San Juan de Colón', 7.7602, -72.2186),
    ('Concha Acústica Bello Monte', '', 'Miranda', 'Avenida Tocuyo, Colinas de Bello Monte, Bello Monte, Caracas', 10.4401, -66.8212),
    ('CC Talislandia Prebo', '', 'Carabobo', 'Centro Comercial Talislandia, Avenida Monseñor Adams, La Ceiba, Prebo, Valencia', 10.1549, -67.9932),
    ('U.E. Nueva Córdoba', '', 'Miranda', 'U.E. Nueva Córdoba, Calle Los Pinos, Pueblo Nuevo, Guarenas', 10.4425, -66.8308),
    ('Club Campestre Los Cortijos', '', 'Miranda', 'Club Campestre Los Cortijos, Avenida Roma, La California Norte, Caracas', 10.4313, -66.8124),
    ('Polideportivo Los Naranjos', 'Asociación de Jóvenes Empresarios', 'Miranda', 'Polideportivo Los Naranjos, Av. Este 3, Los Naranjos, Caracas', 10.4449, -66.8172),
    ('Centro Principal Guasdualito', '', 'Apure', 'Morrones, Guasdualito, Parroquia Guasdualito', 7.2417, -70.7586),
    ('Redoma Gran Mariscal', '', 'Aragua', 'Avenida Gran Mariscal, Corinsa, Cagua', 10.2581, -67.5998),
    ('Plaza Grande Tronconal 5to', '', 'Carabobo', 'Calle 11, Sector 2 de Tronconal, Urbanización Tronconal, Valencia', 10.1621, -67.9988),
    ('Centro de Acopio UCV', 'UCV', 'Distrito Capital', 'Universidad Central de Venezuela, Plaza Rectorado, Ciudad Universitaria, Caracas', 10.4694, -66.894),
    ('Quinta Garrochal', '', 'Miranda', 'Calle los Mangos con Av. San Miguel, diagonal Iglesia Nuestra Señora del Pompei, Urb. Alta Florida, Caracas', 10.4385, -66.818),
    ('Farmatodo La Matica', 'Farmatodo', 'Aragua', 'Farmatodo, Carretera Panamericana, La Matica, Maracay', 10.2381, -67.5958),
    ('UNET Enfermería', 'UNET', 'Táchira', 'Enfermería UNET, Avenida Perimetral UNET, Barrio El Lobo, San Cristóbal', 7.7746, -72.2298),
    ('Rectorado UNEFM', 'UNEFM', 'Falcón', 'UNEFM Rectorado, Calle Norte, Casco Histórico, Coro', 11.687, -70.2106),
    ('Acopio Cartanal', '', 'Miranda', 'Los Güires, Cartanal, Parroquia Cartanal, Miranda', 10.4433, -66.814),
    ('Edificio Murachi', '', 'Aragua', 'Avenida Bolívar, Urbanización Las Acacias, Bella Vista, Maracay', 10.2429, -67.5918),
    ('Complejo Vicente Durán Punto Fijo', '', 'Falcón', 'Complejo Académico Ing. Vicente Durán, Punto Fijo', 11.703, -70.2018),
    ('Econoquesos', '', 'Carabobo', '5ta Transversal, Urbanización Los Mangles, Parcelamiento Miranda, Valencia', 10.1605, -67.9956),
    ('Parroquia Nuestra Señora de Guadalupe', '', 'Mérida', 'Carrera 4 entre calles 2 y 3, Andrés Eloy Blanco, Mérida', 8.6017, -71.1665),
    ('Acopio Lazos de Esperanza', 'Lazos de Esperanza', 'Miranda', 'Calle 29 de Julio, Guarenas', 10.4369, -66.8148),
    ('Hogar Honim', 'Honim', 'Lara', 'Carrera 1 con Calle 4, El Supire, Carrera 27-A, Barquisimeto', 10.0543, -69.3538),
    ('Universidad de Oriente', 'UDO', 'Sucre', 'Parada UDO, Vía Alterna, Parcelamiento Universidad, Cumaná', 10.4562, -64.1842),
    ('Acopio San Juan de Colón (Fucsia)', '', 'Táchira', 'Casco Central, San Juan de Colón, Parroquia Colón', 7.7618, -72.2314),
    ('Acopio Cestas Plásticas CR', '', 'Miranda', 'Carretera Panamericana, Lomas de Urquía, Carrizal', 10.4417, -66.834),
    ('Complejo Cultural San Antonio', '', 'Miranda', 'Complejo Deportivo Recreativo y Cultural Los Salias, San Antonio de los Altos', 10.4305, -66.8156),
    ('Las Cachapas de Félix', '', 'Mérida', 'Claro, Avenida Naciones Unidas, Voz de los Andes, Mérida', 8.5977, -71.1537),
    ('SUMIPAN Market', '', 'Aragua', 'San Jacinto, Maracay', 10.2437, -67.5982),
    ('Plaza Bolívar El Tocuyo', '', 'Lara', 'Avenida Lisandro Alvarado, El Tocuyo', 10.0751, -69.3642),
    ('CSA Ángel Pérez La Pastora', 'Comando Con Venezuela', 'Lara', 'La Pastora, Parroquia Cecilio Zubillaga, Municipio Torres, Lara', 10.0639, -69.3458),
    ('Acopio Voluntad Popular La Toñona', 'Voluntad Popular', 'Anzoátegui', 'Escuela Ramón Pompilio Oropeza, Av. Francisco de Miranda, La Toñona, Anzoátegui', 10.2213, -64.6269),
    ('Acopio Recíbelo Ya', 'Recíbelo Ya', 'Miranda', 'Calle Bolívar, El Toronjil, San Antonio de los Altos', 10.4377, -66.8212),
    ('Tibisay Hotel Boutique', '', 'Falcón', 'Tucacas, Parroquia Tucacas, Municipio Silva', 11.6838, -70.2042),
    ('Alcaldía Libertador Mérida', '', 'Mérida', 'Mérida, Parroquia El Llano, Municipio Libertador', 8.5937, -71.1641),
    ('Iglesia Sion', '', 'Lara', 'Carrera 13C entre calles 45 y 46, Barquisimeto', 10.0575, -69.3466),
    ('THE PLACE Chuao', '', 'Miranda', 'Calle Santa Cruz, Chuao, Lomas de Chuao, Caracas', 10.4425, -66.8172),
    ('Colegio Mater Salvatoris', '', 'Miranda', 'Colegio Mater Salvatoris, Av. Principal de Las Mercedes, Las Mercedes, Caracas', 10.4313, -66.822),
    ('Hospitour Barquisimeto', '', 'Lara', 'Carrera 25, Macuto, Barquisimeto', 10.0735, -69.361),
    ('Amelie Cafe Maracaibo', '', 'Zulia', 'Avenida 3Y, Parroquia Olegario Villalobos, Maracaibo', 10.6642, -71.6212),
    ('Hotel Jirahara', '', 'Lara', 'Calle 6, Urbanización Nueva Segovia, Barquisimeto', 10.0759, -69.3474),
    ('Sede Fly251 Barquisimeto', 'Fly251', 'Lara', 'Aeropuerto Jacinto Lara, Av. La Salle, Barquisimeto', 10.0647, -69.3522)
)
insert into centros_acopio (nombre, organizacion, estado_vzla, direccion, lat, lng, horario, notas)
select s.nombre, s.organizacion, s.estado_vzla, s.direccion, s.lat, s.lng,
       coalesce(h.horario, 'Por confirmar'), '__seed_centros_v2__'
from seed s
left join (values
    ('ISO HOME Prebo', 'Por confirmar'),
    ('ISO HOME El Nepe', 'Por confirmar'),
    ('La Sagrada Familia', 'Por confirmar'),
    ('Centro de Acopio Iglú Moda', 'Por confirmar'),
    ('Rock and Rolls Fit', 'Por confirmar'),
    ('Páramo Qta Crespo', 'Por confirmar'),
    ('Bullking Qta Crespo', 'Por confirmar'),
    ('Bullking Paraíso', 'Por confirmar'),
    ('Bullking Antímano', '8AM-5PM'),
    ('U.E.N. Ramón Isidro Montes', '8am-5pm'),
    ('Iglesia Catedral Proclamación', '24 horas'),
    ('Acopio Parroquia Coche', 'Lun-Dom 8:00-20:00'),
    ('Casa Verde Cincoxciento', 'Por confirmar'),
    ('Shopping Espacial Piso 2', '2pm-8pm'),
    ('INTT San Juan de los Morros', 'Por confirmar'),
    ('Farmatodo María de los Ángeles', 'Por confirmar'),
    ('Estación de Servicio Pariapan', 'Por confirmar'),
    ('Alcaldía Juan Germán Roscio', 'Por confirmar'),
    ('Acopio Tamaca', 'Por confirmar'),
    ('Via Venetto', '8am-6pm'),
    ('Gobernación de Guárico', 'Por confirmar'),
    ('Shopping Off San Juan', 'Por confirmar'),
    ('Una Mano Amiga Doña Elvira', 'Por confirmar'),
    ('Biblioteca Rómulo Gallegos SJM', 'Por confirmar'),
    ('Una Mano Amiga Plaza Samanes', 'Por confirmar'),
    ('Acopio Parroquia El Valle', '8am-5pm'),
    ('Bomberos de Guacara', 'Siempre abierto'),
    ('Colegio Caribe', 'Lun-Dom 9:00-17:00'),
    ('Academia Washington', 'Vie 26-Dom 28 9:00-16:00'),
    ('Capilla UCAB', 'A partir de las 8am'),
    ('Logística Vincars', 'Viernes 08:00-14:00'),
    ('Plaza de la Bandera Pampatar', 'Por confirmar'),
    ('Bomberos La Trinidad', 'Por confirmar'),
    ('Gran Slam Covencaucho', 'Por confirmar'),
    ('Centro Médico La Candelaria Cúa', 'Vie 8:00-17:00'),
    ('Iglesia Maranatha Valencia', '24h'),
    ('Reda Estate', 'Por confirmar'),
    ('Frente CC Cima Barinas', 'Por confirmar'),
    ('Alcaldía Roscio Nieves', 'Por confirmar'),
    ('Rectorado UNERG', 'Por confirmar'),
    ('Cafetín Clínica Santa Rosalía', 'Por confirmar'),
    ('Alcaldía de San Francisco', 'Por confirmar'),
    ('U.E. Kavac Prebo', 'Jueves y Viernes'),
    ('Plaza Los Samanes SJM', '2pm'),
    ('Kawaii Multitienda Marconi', 'Por confirmar'),
    ('Cavernícolas Box', 'Por confirmar'),
    ('Los Andes 2 San Diego', 'Por confirmar'),
    ('Casona Universitaria', 'Por confirmar'),
    ('Callejón Gourmet', 'Por confirmar'),
    ('Centro de Acopio Despistaje Cáncer', '7am-3pm'),
    ('Ciudad Banesco', 'Vie 9am-4pm'),
    ('Cadoven Sambil', 'Por confirmar'),
    ('Fundación Juntos Se Puede', 'Por confirmar'),
    ('CC Borjas Xtrema', 'Por confirmar'),
    ('Iglesia La Chiquinquirá', 'Por confirmar'),
    ('Pepitería 13', 'Por confirmar'),
    ('Instituto Diseño Caracas', 'Por confirmar'),
    ('Academia Merici', 'Por confirmar'),
    ('UNERG Paraíso', 'Por confirmar'),
    ('ULA Paramillo', '8am-4pm'),
    ('Acopio Abasto Caracas', '9am-9pm'),
    ('Acopio Candelaria Galerías Ávila', 'Por confirmar'),
    ('Capilla Divina Pastora Caracas', '19:00-21:00'),
    ('Acopio Las Mercedes Barriot', 'Por confirmar'),
    ('TSJ San Juan de Colón', '9am-7pm'),
    ('Concha Acústica Bello Monte', '9am-7pm'),
    ('CC Talislandia Prebo', 'Por confirmar'),
    ('U.E. Nueva Córdoba', '8:00-15:00'),
    ('Club Campestre Los Cortijos', 'Por confirmar'),
    ('Polideportivo Los Naranjos', 'Por confirmar'),
    ('Centro Principal Guasdualito', 'Por confirmar'),
    ('Redoma Gran Mariscal', 'Por confirmar'),
    ('Plaza Grande Tronconal 5to', '2-8pm'),
    ('Centro de Acopio UCV', 'Por confirmar'),
    ('Quinta Garrochal', 'Por confirmar'),
    ('Farmatodo La Matica', 'Hasta 4pm'),
    ('UNET Enfermería', 'Por confirmar'),
    ('Rectorado UNEFM', 'Vie 26 y Sáb 27 9:00-17:00'),
    ('Acopio Cartanal', 'Por confirmar'),
    ('Edificio Murachi', 'Por confirmar'),
    ('Complejo Vicente Durán Punto Fijo', 'Jue 25/06 17:00, Vie 26/06 9:00-17:00'),
    ('Econoquesos', 'Por confirmar'),
    ('Parroquia Nuestra Señora de Guadalupe', 'Por confirmar'),
    ('Acopio Lazos de Esperanza', 'Por confirmar'),
    ('Hogar Honim', 'Por confirmar'),
    ('Universidad de Oriente', 'Sáb-Dom 8:00-11:00'),
    ('Acopio San Juan de Colón (Fucsia)', '6pm'),
    ('Acopio Cestas Plásticas CR', 'Hoy por la tarde'),
    ('Complejo Cultural San Antonio', 'Todo el día'),
    ('Las Cachapas de Félix', 'Desde 11am'),
    ('SUMIPAN Market', 'Por confirmar'),
    ('Plaza Bolívar El Tocuyo', 'Por confirmar'),
    ('CSA Ángel Pérez La Pastora', 'Lun-Dom 7:00-22:00'),
    ('Acopio Voluntad Popular La Toñona', 'Por confirmar'),
    ('Acopio Recíbelo Ya', 'Todo el día'),
    ('Tibisay Hotel Boutique', 'Por confirmar'),
    ('Alcaldía Libertador Mérida', 'Por confirmar'),
    ('Iglesia Sion', 'Jueves a Domingo'),
    ('THE PLACE Chuao', 'Por confirmar'),
    ('Colegio Mater Salvatoris', 'Por confirmar'),
    ('Hospitour Barquisimeto', 'Por confirmar'),
    ('Amelie Cafe Maracaibo', 'Por confirmar'),
    ('Hotel Jirahara', 'Por confirmar'),
    ('Sede Fly251 Barquisimeto', 'Por confirmar')
) as h(nombre, horario) on h.nombre = s.nombre
where not exists (
  select 1 from centros_acopio c where c.nombre = s.nombre
);

